# Generated by Django 2.0 on 2018-01-01 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkid', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shortenURL', models.CharField(max_length=500, unique=True)),
                ('targetURL', models.CharField(max_length=500)),
            ],
        ),
    ]
